// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoSMgN-v7-PE5dEJgJCURFIgFyfhsT_c',
    appId: '1:175212374401:web:723de224f408c5b84c6080',
    messagingSenderId: '175212374401',
    projectId: 'efficio-320f8',
    authDomain: 'efficio-320f8.firebaseapp.com',
    storageBucket: 'efficio-320f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTN4L4UElpVSs5lcl4AjDydQRz1sBixQ',
    appId: '1:175212374401:android:06a06619e8cbe78c4c6080',
    messagingSenderId: '175212374401',
    projectId: 'efficio-320f8',
    storageBucket: 'efficio-320f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8U9R_hbsL0-jYbGhebopltm58ZpP05tk',
    appId: '1:175212374401:ios:7d46348717b6c7ff4c6080',
    messagingSenderId: '175212374401',
    projectId: 'efficio-320f8',
    storageBucket: 'efficio-320f8.firebasestorage.app',
    iosBundleId: 'com.example.efficio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8U9R_hbsL0-jYbGhebopltm58ZpP05tk',
    appId: '1:175212374401:ios:7d46348717b6c7ff4c6080',
    messagingSenderId: '175212374401',
    projectId: 'efficio-320f8',
    storageBucket: 'efficio-320f8.firebasestorage.app',
    iosBundleId: 'com.example.efficio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVoSMgN-v7-PE5dEJgJCURFIgFyfhsT_c',
    appId: '1:175212374401:web:e32eaaabc286e1a24c6080',
    messagingSenderId: '175212374401',
    projectId: 'efficio-320f8',
    authDomain: 'efficio-320f8.firebaseapp.com',
    storageBucket: 'efficio-320f8.firebasestorage.app',
  );
}
